### ISSUE TITLE
Web page analytics

### ISSUE THREAD

**Issue by giwa** [westlab/door-api#26]
- [x] download html
- [x] remove html tags
- [x] from element analytics

**Comment by giwa** [comment]
@momotaro98 

これアサインしてもいい？

任意のURLをダンロードしてhtmlのタグをけすコードを書く。大体ライブラリ使えばできる。

**Comment by momotaro98** [comment]
@giwa 
大丈夫です。

`html`タグが 無いHTMLテキストを返すだけでよいのでしょうか。

**Comment by giwa** [comment]
まずはそれだけでいいです。
次のステップとして、単語を kagomeというlibを使って形態要素解析をし取り出します。

html のtagを取るのはこれを使うといいも思う。他にもあるかもしれないから調べてみて
https://github.com/kennygrant/sanitize

**Comment by giwa** [comment]
HTTPのリクエストに関しては、少しここを読むといい
http://qiita.com/umisama/items/46094fce4a2dcef091b4

今回は同じホストに複数回問い合わせるのは殆ど無いのであまり意味ないかもだけど、TCPのコネクション使う回そうねという意図のものです。

**Comment by giwa** [comment]
`func DownloadHTML(url string) (html string)`

`func RemoveHTMLTags(html string) (text string)`

上記の関数を実装して欲しい。

**Comment by giwa** [comment]
場所はこのファイルにかいてください。
https://github.com/westlab/door-api/blob/develop/job/html_analyzer.go

**Comment by momotaro98** [comment]
@giwa 
ありがとうございます。了解です。

**Comment by giwa** [comment]
@momotaro98 
次のタスク

https://github.com/ikawaha/kagome
を使ってテキストから名詞のみを抜き出す。

そのワードをカウントする関数

`func GetNouns(text string) (words []string)`

`func WrodCount(words []string) []Count`

を実装してください。

**Comment by giwa** [comment]
``` go
package main

import (
    "fmt"
    "strings"

    "github.com/ikawaha/kagome/tokenizer"
)

func main() {
    t := tokenizer.New()
    tokens := t.Tokenize("涼宮ハルヒ")

    for _, token := range tokens {
        if token.Class == tokenizer.DUMMY {
            fmt.Printf("%s\n", token.Surface)
            continue
        }
        features := strings.Join(token.Features(), ",")
        fmt.Printf("%s\t%v\n", token.Surface, features)
    }
}
```

```
$ go run main.go
涼 名詞,一般,*,*,*,*,涼,リョウ,リョー
宮 名詞,一般,*,*,*,*,宮,ミヤ,ミヤ
ハルヒ   名詞,一般,*,*,*,*,*
EOS

```

サンプル
